package icu.takeneko.omms.central.permission;

public enum Permission {
    // 0
    SERVER_OS_CONTROL,
    CENTRAL_SERVER_CONTROL,
    PERMISSION_LIST,
    PERMISSION_MODIFY,
    RESERVED_2,
    CONTROLLER_CONTROL,
    CONTROLLER_CREATE,
    WHITELIST_ADD,
    WHITELIST_REMOVE,
    WHITELIST_CREATE,
    WHITELIST_DELETE,
    RESERVED_1,
    ANNOUNCEMENT_CREATE,
    ANNOUNCEMENT_DELETE,
    ANNOUNCEMENT_MODIFY,
    EXECUTE_PLUGIN_REQUEST;
    // 15
}
